### ISSUE TITLE
Create helm chart to deploy quickly on kubernetes

### ISSUE THREAD

**Issue by reesericci** [hackclub/AssembleTicketing-Backend#7]
Hi @tetraoxygen !

I would really appreciate it if you would consider making a helm chart, that way I can spin this up easily on kubernetes.

Thank you!

--reese

**Comment by reesericci** [comment]
cc @YodaLightsabr

**Comment by reesericci** [comment]
Why was this closed? There was no reasoning provided.

**Comment by YodaLightsabr** [comment]
The reasoning is "not planned".
In all seriousness though, this probably isn't something we'll do for Assemble Ticketing.

**Comment by YodaLightsabr** [comment]
We should consider making a deployment guide though.

**Comment by reesericci** [comment]
It would make it much easier to deploy for people though. Instead of spinning up two seperate linodes and a frontend, they just create a managed k8s cluster and deploy the chart.
